name: Issue Generator
on:
  issues:
    types: 
      - opened
  
jobs:
  issue-generator: 
    runs-on: ubuntu-latest
    permissions:
      issues: read/write
    if: contains(github.event.issue.*.name, 'bug')
    steps:
       - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
       - run: ls ${{ github.workspace }}
       - name: Create team sync issue
         uses: imjohnbo/issue-bot@3d96848fb5e9a4a473bb81ae62b4b4866a56e93a
         with:
            assignees: "MarkusSchramm"
            labels: "bug"
            title: "Team sync"
            body: |
              ### Agenda
              - [ ] Start the recording
              - [ ] Check-ins
              - [ ] Discussion points
              - [ ] Post the recording
                    
              ### Discussion Points
              Add things to discuss below
              - [Work this week](https://github.com/users/BlueberryMountainStudio/projects/3
    
env:
  GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
